#name =input ("what is you're name: ")
age =int(input("how old are you: "))
#print(name)
print(age)
print("you are "+ str(age)+" years old")
print(type(age))
height =float(input("how tall are you: "))
print(type(height))
print("you are "+str(height)+ "cm tall")